### ISSUE TITLE
Редактирование фотографий 

### ISSUE THREAD

**Issue by khaydarov** [ProNWE/service#22]
- [x] @kolyasha 

- [ ] @unvir 

- [ ] @khaydarov

**Comment by kolyasha** [comment]
Предлагаю создать свой модель загрузки фотографий, использую cropper и upload

**Comment by kolyasha** [comment]
нужно запретить "копирование" файла вне зоне drag and drop

**Comment by kolyasha** [comment]
Фронт сделан, осталось сделать обработчик полученного изображения на бэке, получаемые параметры: id, file, cropdata.
