### ISSUE TITLE
Создание мероприятия

### ISSUE THREAD

**Issue by kolyasha** [ProNWE/service#57]
При создание мероприятия, не сохраняется информация о пользователях, имеющих к нему доступ, а также сохраняется только последнее keyword.

**Comment by khaydarov** [comment]
1) что имеется ввиду по словом keywords? Где она будет использована ?

**Comment by kolyasha** [comment]
keywords будет использоваться на странице мероприятия. Они нужны для того, чтобы поисковики точнее находили мероприятие:
Description будет браться из столбца short_description
```
<meta name="Description" content="">
<meta name="Keywords" content="">
```
