### ISSUE TITLE
Создать страницу выставления баллов - до 4 декабря

### ISSUE THREAD

**Issue by kolyasha** [ProNWE/service#72]
Выставление баллов участникам (командам) с помощью смартфонов.
Что-то наподобие "Приз зрительских симпатий".

Можно поместить на странице мероприятия, причем когда хочешь посмотреть результаты "приз зрительских симпатий", тебе нужно проголосовать (наподобие голосование в вк).

**Comment by unvir** [comment]
Может, стоит вместить это в лендинг мероприятия?

**Comment by khaydarov** [comment]
я тоже думаю, что нужно как-то в лендинг вместить

**Comment by kolyasha** [comment]
Я это и имел в виду =) Есть идея сделать просмотр результатов по вкладкам (tabs), и в одно из этих поместить эту голосовалку
