### ISSUE TITLE
Проверить подключение фирменного шрифта на всех страницах

### ISSUE THREAD

**Issue by kolyasha** [ProNWE/service#9]

**Comment by khaydarov** [comment]
пиши описание, пожалуйста[

**Comment by kolyasha** [comment]
Нужно проверить, что наш стиль шрифта подключён,  так как Петя заметил, что он не везде отображается корректно, где то в каких то cuss перегружен

**Comment by khaydarov** [comment]
Тогда в bugs добавляем эти страницы и, желательно, скрин. Будет круто если будем описывать конкретно задачу, обоснуем что он важен и нужно именно в issues добавить

**Comment by kolyasha** [comment]
Ок
